spring.application.name=pokemon

spring.datasource.url=jdbc:mysql://5.tcp.ngrok.io:29865/base16
spring.datasource.username=estudiantedes3
spring.datasource.password=desarrollo2026$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
